Vagrant.configure("2") do |config|
  config.vm.box = "mcandre/vagrant-void-haskell-i386"
  config.vm.box_version = "0.0.1"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 4096 # MiB
  end

  # Prepare for vagrant package
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: true

  config.vm.provision "shell", path: "bootstrap.sh", privileged: false
end
