#!/bin/sh
set -euf
unset IFS

apt-get update
apt-get install -y \
    cmake \
    cppcheck \
    git \
    make \
    python3-pip \
    python3-setuptools \
    valgrind \
    vera++
echo "export PATH=\"\$PATH:/home/vagrant/.local/bin\"" >>/etc/profile
cp -r /usr/lib/vera++ /home/vagrant/.vera++
ln -sf /vagrant/vera /home/vagrant/.vera++/profiles/default
apt-get clean -y
rm -rf /var/lib/apt/lists/* \
    /var/cache/apt/pkgcache.bin \
    /var/cache/apt/srcpkgcache.bin

pip3 install wheel
pip3 install cpplint

git clone https://github.com/mcandre/sail.git /home/vagrant/sail
echo "export PATH=\"\$PATH:/home/vagrant/sail/bin\"" >>/etc/profile
