Vagrant.configure("2") do |config|
    config.vm.box = "kishikawakatsumi/macos-catalina-xcode12"

    # Prepare for vagrant package
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", type: "rsync", disabled: true

    config.vm.provision "file", source: "requirements-dev.txt", destination: "/tmp/requirements-dev.txt"
    config.vm.provision "shell", path: "bootstrap", privileged: false
end
